// ============================================
// ДАННЫЕ - Расширенный справочник марок
// ============================================

// Справочник марок и моделей (РАСШИРЕННЫЙ)
const BRANDS_DATA = {
  car: {
    'Abarth': ['124 Spider', '500', '595', '695'],
    'Acura': ['ILX', 'MDX', 'NSX', 'RDX', 'TLX', 'ZDX'],
    'Alfa Romeo': ['Giulia', 'Giulietta', 'Stelvio', '159', '147', 'MiTo', '4C'],
    'Aston Martin': ['DB11', 'DBX', 'Vantage', 'Rapide', 'DBS'],
    'Audi': ['A1', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'Q2', 'Q3', 'Q5', 'Q7', 'Q8', 'TT', 'R8', 'e-tron', 'RS3', 'RS4', 'RS5', 'RS6', 'RS7', 'SQ5', 'SQ7'],
    'Bentley': ['Bentayga', 'Continental', 'Flying Spur', 'Mulsanne'],
    'BMW': ['1 Series', '2 Series', '3 Series', '4 Series', '5 Series', '6 Series', '7 Series', '8 Series', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'Z4', 'i3', 'i4', 'i8', 'iX', 'M2', 'M3', 'M4', 'M5', 'M8'],
    'Bugatti': ['Chiron', 'Veyron'],
    'Buick': ['Enclave', 'Encore', 'Envision', 'LaCrosse', 'Regal'],
    'BYD': ['Han', 'Tang', 'Song', 'Yuan Plus', 'Qin', 'Seal', 'Atto 3', 'Dolphin'],
    'Cadillac': ['CT4', 'CT5', 'CT6', 'Escalade', 'XT4', 'XT5', 'XT6', 'Lyriq'],
    'Chery': ['Tiggo 4', 'Tiggo 7', 'Tiggo 8', 'Arrizo 5', 'Arrizo 6', 'Exeed TXL'],
    'Chevrolet': ['Blazer', 'Camaro', 'Corvette', 'Cruze', 'Equinox', 'Malibu', 'Silverado', 'Spark', 'Suburban', 'Tahoe', 'Traverse', 'Trax'],
    'Chrysler': ['300', 'Pacifica', 'Voyager'],
    'Citroen': ['C1', 'C3', 'C4', 'C5', 'Berlingo', 'Jumpy', 'SpaceTourer'],
    'Dacia': ['Duster', 'Logan', 'Sandero', 'Spring'],
    'Daewoo': ['Gentra', 'Nexia', 'Matiz'],
    'Daihatsu': ['Terios', 'Sirion', 'Copen'],
    'Dodge': ['Challenger', 'Charger', 'Durango', 'Journey', 'RAM 1500'],
    'Ferrari': ['296 GTB', '488', '812', 'F8', 'Portofino', 'Roma', 'SF90'],
    'Fiat': ['500', '500X', 'Panda', 'Tipo', 'Ducato'],
    'Ford': ['Bronco', 'Edge', 'EcoSport', 'Escape', 'Explorer', 'F-150', 'Fiesta', 'Focus', 'Fusion', 'Kuga', 'Mondeo', 'Mustang', 'Ranger', 'Transit'],
    'Geely': ['Atlas', 'Coolray', 'Emgrand', 'Monjaro', 'Tugella', 'Geometry C'],
    'Genesis': ['G70', 'G80', 'G90', 'GV60', 'GV70', 'GV80'],
    'GMC': ['Acadia', 'Canyon', 'Sierra', 'Terrain', 'Yukon'],
    'Great Wall': ['Hover H3', 'Hover H5', 'Hover H6', 'Hover H9', 'Poer', 'Wingle'],
    'Haval': ['F7', 'H2', 'H6', 'H9', 'Jolion', 'Dargo'],
    'Honda': ['Accord', 'Civic', 'City', 'CR-V', 'CR-Z', 'Fit', 'HR-V', 'Insight', 'Jazz', 'Odyssey', 'Passport', 'Pilot', 'Ridgeline'],
    'Hummer': ['H2', 'H3', 'EV'],
    'Hyundai': ['Accent', 'Creta', 'Elantra', 'i10', 'i20', 'i30', 'i40', 'Ioniq 5', 'Ioniq 6', 'Kona', 'Palisade', 'Santa Fe', 'Solaris', 'Sonata', 'Staria', 'Tucson', 'Veloster'],
    'Infiniti': ['Q50', 'Q60', 'Q70', 'QX30', 'QX50', 'QX55', 'QX60', 'QX80'],
    'Isuzu': ['D-Max', 'MU-X'],
    'Jaguar': ['E-Pace', 'F-Pace', 'F-Type', 'I-Pace', 'XE', 'XF', 'XJ'],
    'Jeep': ['Cherokee', 'Commander', 'Compass', 'Gladiator', 'Grand Cherokee', 'Renegade', 'Wrangler'],
    'Kia': ['Carens', 'Carnival', 'Ceed', 'EV6', 'K5', 'Mohave', 'Niro', 'Optima', 'Picanto', 'Rio', 'Seltos', 'Sorento', 'Soul', 'Sportage', 'Stinger', 'Stonic'],
    'Lada': ['Granta', 'Kalina', 'Largus', 'Niva', 'Vesta', 'XRAY'],
    'Lamborghini': ['Aventador', 'Huracan', 'Urus'],
    'Lancia': ['Ypsilon', 'Delta'],
    'Land Rover': ['Defender', 'Discovery', 'Discovery Sport', 'Range Rover', 'Range Rover Evoque', 'Range Rover Sport', 'Range Rover Velar'],
    'Lexus': ['CT', 'ES', 'GS', 'GX', 'IS', 'LC', 'LS', 'LX', 'NX', 'RC', 'RX', 'UX'],
    'Lincoln': ['Aviator', 'Corsair', 'Navigator', 'Nautilus'],
    'Lotus': ['Elise', 'Emira', 'Evora', 'Exige'],
    'Maserati': ['Ghibli', 'GranTurismo', 'Levante', 'MC20', 'Quattroporte'],
    'Maybach': ['S-Class', 'GLS'],
    'Mazda': ['2', '3', '6', 'CX-3', 'CX-30', 'CX-5', 'CX-50', 'CX-60', 'CX-9', 'CX-90', 'MX-5', 'MX-30'],
    'McLaren': ['570S', '720S', 'Artura', 'GT'],
    'Mercedes': ['A-Class', 'B-Class', 'C-Class', 'CLA', 'CLS', 'E-Class', 'G-Class', 'GLA', 'GLB', 'GLC', 'GLE', 'GLS', 'S-Class', 'V-Class', 'EQA', 'EQB', 'EQC', 'EQE', 'EQS', 'AMG GT'],
    'MG': ['3', '5', '6', 'HS', 'ZS', 'Marvel R'],
    'Mini': ['Clubman', 'Countryman', 'Cooper', 'Paceman'],
    'Mitsubishi': ['ASX', 'Eclipse Cross', 'L200', 'Lancer', 'Outlander', 'Pajero', 'Pajero Sport'],
    'Nissan': ['370Z', 'Almera', 'Ariya', 'GT-R', 'Juke', 'Kicks', 'Leaf', 'Micra', 'Murano', 'Navara', 'Note', 'Pathfinder', 'Patrol', 'Qashqai', 'Sentra', 'Terrano', 'Titan', 'X-Trail'],
    'Opel': ['Astra', 'Corsa', 'Crossland', 'Grandland', 'Insignia', 'Mokka', 'Zafira'],
    'Peugeot': ['108', '208', '2008', '308', '3008', '408', '508', '5008', 'Boxer', 'Partner', 'Rifter', 'Traveller'],
    'Porsche': ['718', '911', 'Cayenne', 'Macan', 'Panamera', 'Taycan'],
    'RAM': ['1500', '2500', '3500'],
    'Renault': ['Arkana', 'Captur', 'Clio', 'Duster', 'Espace', 'Kadjar', 'Kangoo', 'Kaptur', 'Koleos', 'Logan', 'Megane', 'Sandero', 'Scenic', 'Talisman'],
    'Rolls-Royce': ['Cullinan', 'Ghost', 'Phantom', 'Wraith'],
    'Saab': ['9-3', '9-5'],
    'Seat': ['Arona', 'Ateca', 'Ibiza', 'Leon', 'Tarraco'],
    'Skoda': ['Fabia', 'Kamiq', 'Karoq', 'Kodiaq', 'Octavia', 'Rapid', 'Scala', 'Superb'],
    'Smart': ['ForTwo', 'ForFour'],
    'SsangYong': ['Korando', 'Rexton', 'Tivoli'],
    'Subaru': ['BRZ', 'Crosstrek', 'Forester', 'Impreza', 'Legacy', 'Outback', 'WRX', 'XV'],
    'Suzuki': ['Grand Vitara', 'Ignis', 'Jimny', 'S-Cross', 'Swift', 'SX4', 'Vitara'],
    'Tesla': ['Model 3', 'Model S', 'Model X', 'Model Y', 'Cybertruck', 'Roadster'],
    'Toyota': ['4Runner', '86', 'Alphard', 'Aqua', 'Auris', 'Avalon', 'Avensis', 'bZ4X', 'C-HR', 'Camry', 'Corolla', 'Crown', 'FJ Cruiser', 'Fortuner', 'Highlander', 'Hilux', 'Land Cruiser', 'Land Cruiser Prado', 'Mirai', 'Prius', 'RAV4', 'Sequoia', 'Supra', 'Tacoma', 'Tundra', 'Venza', 'Yaris'],
    'UAZ': ['Hunter', 'Patriot', 'Pickup'],
    'Volkswagen': ['Amarok', 'Arteon', 'Atlas', 'Beetle', 'Caddy', 'CC', 'Golf', 'ID.3', 'ID.4', 'Jetta', 'Multivan', 'Passat', 'Polo', 'T-Cross', 'T-Roc', 'Taos', 'Tiguan', 'Touareg', 'Touran', 'Transporter'],
    'Volvo': ['C40', 'S60', 'S90', 'V60', 'V90', 'XC40', 'XC60', 'XC90']
  },
  
  truck: {
    'DAF': ['CF', 'LF', 'XF', 'XG', 'XG+'],
    'Freightliner': ['Cascadia', 'Columbia', 'Coronado', 'M2'],
    'Hino': ['300', '500', '700'],
    'Hyundai': ['HD65', 'HD72', 'HD78', 'Mighty', 'Porter'],
    'Isuzu': ['Elf', 'Forward', 'Giga'],
    'Iveco': ['Daily', 'Eurocargo', 'Stralis', 'Trakker', 'S-Way'],
    'Kamaz': ['43118', '5490', '6520', '65115', '65207'],
    'Kenworth': ['T680', 'T880', 'W900'],
    'MAN': ['TGE', 'TGL', 'TGM', 'TGS', 'TGX'],
    'Mack': ['Anthem', 'Granite', 'Pinnacle'],
    'MAZ': ['5440', '6430', '6501'],
    'Mercedes': ['Actros', 'Antos', 'Arocs', 'Atego', 'Axor', 'Sprinter'],
    'Peterbilt': ['389', '579', '567'],
    'Renault': ['C', 'D', 'K', 'T', 'Master'],
    'Scania': ['G', 'P', 'R', 'S'],
    'Volvo': ['FE', 'FL', 'FM', 'FMX', 'FH', 'FH16'],
    'Western Star': ['4700', '4900', '5700']
  },
  
  special: {
    'Bobcat': ['S70', 'S100', 'S150', 'S205', 'T76'],
    'Case': ['580', '721F', '821F', 'CX130', 'CX210'],
    'Caterpillar': ['303.5', '312', '315', '320', '325', '330', '336', '345', '349', '950', '966', '972'],
    'Doosan': ['DH130', 'DH220', 'DX225', 'DX300', 'DX420', 'DX530'],
    'Hitachi': ['EX100', 'EX200', 'ZX210', 'ZX250', 'ZX330', 'ZX470'],
    'Hyundai': ['R140', 'R180', 'R210', 'R300', 'R450', 'R520'],
    'JCB': ['3CX', '4CX', '5CX', 'JS130', 'JS160', 'JS220', 'JS330'],
    'John Deere': ['120', '135', '160', '210', '310', '410'],
    'Komatsu': ['PC130', 'PC160', 'PC200', 'PC210', 'PC300', 'PC360', 'PC450'],
    'Liebherr': ['R914', 'R924', 'R934', 'R944', 'R954'],
    'New Holland': ['B90B', 'B110B', 'E135', 'E215'],
    'Terex': ['HR18', 'HR32', 'TL80', 'TL120'],
    'Volvo': ['EC140', 'EC160', 'EC210', 'EC240', 'EC300', 'EC380', 'EC480']
  },
  
  moto: {
    'Aprilia': ['RS 660', 'RSV4', 'Tuono', 'Dorsoduro'],
    'Benelli': ['TNT 600', 'Leoncino', 'TRK 502'],
    'BMW': ['F 750 GS', 'F 850 GS', 'R 1250 GS', 'R nineT', 'S 1000 RR', 'S 1000 XR'],
    'Ducati': ['Diavel', 'Monster', 'Multistrada', 'Panigale', 'Scrambler', 'SuperSport'],
    'Harley': ['Fat Boy', 'Iron 883', 'Road King', 'Softail', 'Sportster', 'Street', 'Street Glide', 'Touring'],
    'Honda': ['Africa Twin', 'CB500', 'CB650', 'CB1000', 'CBR600', 'CBR1000', 'Gold Wing', 'NC750', 'Rebel'],
    'Indian': ['Chief', 'FTR', 'Scout', 'Springfield'],
    'Kawasaki': ['Ninja 400', 'Ninja 650', 'Ninja 1000', 'Versys', 'Vulcan', 'Z650', 'Z900', 'ZX-6R', 'ZX-10R'],
    'KTM': ['390 Duke', '790 Duke', '890 Duke', '1290 Super Duke', 'RC 390'],
    'Moto Guzzi': ['V7', 'V9', 'V85 TT'],
    'MV Agusta': ['Brutale', 'F3', 'Turismo Veloce'],
    'Royal Enfield': ['Classic 350', 'Himalayan', 'Interceptor 650'],
    'Suzuki': ['Boulevard', 'GSX-R600', 'GSX-R750', 'GSX-R1000', 'Hayabusa', 'SV650', 'V-Strom'],
    'Triumph': ['Bonneville', 'Rocket 3', 'Speed Triple', 'Street Triple', 'Tiger'],
    'Yamaha': ['FZ-09', 'MT-07', 'MT-09', 'MT-10', 'R1', 'R6', 'R7', 'Tracer', 'V-Max', 'XSR']
  },
  
  water: {
    'BRP': ['Sea-Doo GTI', 'Sea-Doo GTR', 'Sea-Doo GTX', 'Sea-Doo RXP', 'Sea-Doo RXT', 'Sea-Doo Spark', 'Sea-Doo Wake'],
    'Honda': ['Aquatrax F-12', 'Aquatrax F-15'],
    'Kawasaki': ['Jet Ski STX', 'Jet Ski SX-R', 'Jet Ski Ultra', 'Jet Ski Ultra LX'],
    'Polaris': ['MSX'],
    'Yamaha': ['EX', 'EXR', 'FX', 'FX SVHO', 'GP1800', 'SuperJet', 'VX', 'VX Cruiser', 'VX Deluxe', 'WaveRunner']
  }
};

const categoryNames = {
  car: '🚗 Легковой',
  truck: '🚚 Грузовой',
  special: '🚜 Спецтехника',
  moto: '🏍 Мототехника',
  water: '🚤 Водный'
};

// 98 объявлений (68 было + 30 новых)
function initCarsData() {
  function randomDate(start, end) {
    return new Date(start.getTime() + Math.random() * (end.getTime() - start.getTime()));
  }

  const now = new Date();
  const threeDaysAgo = new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000);
  const sevenDaysAgo = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);
  const monthAgo = new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000);

  return [
    {id:1,category:'car',brand:'Toyota',model:'Camry',year:2020,price:25000,currency:'$',mileage:45000,engine:'2.5 л',transmission:'Автомат',fuel:'Бензин',city:'Тирасполь',registration:'ПМР',description:'Отличное состояние',photos:['https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=400'],isTop:true,createdAt:randomDate(sevenDaysAgo,monthAgo),userId:null},
    {id:2,category:'car',brand:'BMW',model:'X5',year:2019,price:42000,currency:'$',mileage:62000,engine:'3.0 л',transmission:'Автомат',fuel:'Дизель',city:'Кишинёв',registration:'Молдова',description:'Полный привод',photos:['https://images.unsplash.com/photo-1555215695-3004980ad54e?w=400'],isTop:true,createdAt:randomDate(sevenDaysAgo,monthAgo),userId:null},
    {id:3,category:'car',brand:'Mercedes',model:'E-Class',year:2021,price:58000,currency:'€',mileage:28000,engine:'2.0 л',transmission:'Автомат',fuel:'Бензин',city:'Тирасполь',registration:'ПМР',description:'AMG пакет',photos:[],isTop:true,createdAt:randomDate(threeDaysAgo,now),userId:null},
    {id:4,category:'car',brand:'Hyundai',model:'Solaris',year:2022,price:13500,currency:'$',mileage:15000,engine:'1.6 л',transmission:'Автомат',fuel:'Бензин',city:'Рыбница',registration:'ПМР',description:'Новый',photos:[],isTop:false,createdAt:randomDate(threeDaysAgo,now),userId:null},
    {id:5,category:'truck',brand:'Mercedes',model:'Actros',year:2018,price:75000,currency:'€',mileage:280000,engine:'12.8 л',transmission:'Автомат',fuel:'Дизель',city:'Тирасполь',registration:'ПМР',description:'Грузовик',photos:[],isTop:false,createdAt:randomDate(threeDaysAgo,now),userId:null},
    {id:6,category:'moto',brand:'Harley',model:'Sportster',year:2020,price:15000,currency:'$',mileage:8000,engine:'1.2 л',transmission:'Механика',fuel:'Бензин',city:'Кишинёв',registration:'Молдова',description:'Мотоцикл',photos:[],isTop:false,createdAt:randomDate(sevenDaysAgo,monthAgo),userId:null},
    {id:7,category:'special',brand:'Caterpillar',model:'320',year:2017,price:95000,currency:'$',mileage:4500,engine:'4.4 л',transmission:'Гидравлика',fuel:'Дизель',city:'Рыбница',registration:'ПМР',description:'Экскаватор',photos:[],isTop:false,createdAt:randomDate(sevenDaysAgo,monthAgo),userId:null},
    {id:8,category:'water',brand:'Yamaha',model:'VX',year:2021,price:18000,currency:'$',mileage:150,engine:'1.8 л',transmission:'Авто',fuel:'Бензин',city:'Днестровск',registration:'ПМР',description:'Гидроцикл',photos:[],isTop:false,createdAt:randomDate(threeDaysAgo,now),userId:null},
    {id:9,category:'car',brand:'Audi',model:'A4',year:2020,price:35000,currency:'€',mileage:48000,engine:'2.0 л',transmission:'Автомат',fuel:'Бензин',city:'Тирасполь',registration:'ПМР',description:'Quattro',photos:[],isTop:false,createdAt:randomDate(threeDaysAgo,now),userId:null},
    {id:10,category:'car',brand:'Volkswagen',model:'Polo',year:2019,price:12000,currency:'$',mileage:65000,engine:'1.6 л',transmission:'Механика',fuel:'Бензин',city:'Бельцы',registration:'Молдова',description:'Надежный',photos:[],isTop:true,createdAt:randomDate(sevenDaysAgo,monthAgo),userId:null},
    {id:11,category:'car',brand:'Kia',model:'Sportage',year:2021,price:28000,currency:'$',mileage:35000,engine:'2.0 л',transmission:'Автомат',fuel:'Бензин',city:'Кишинёв',registration:'Молдова',description:'Кроссовер',photos:[],isTop:false,createdAt:randomDate(sevenDaysAgo,monthAgo),userId:null},
    {id:12,category:'car',brand:'Mazda',model:'CX-5',year:2020,price:26500,currency:'$',mileage:42000,engine:'2.5 л',transmission:'Автомат',fuel:'Бензин',city:'Рыбница',registration:'ПМР',description:'Полный привод',photos:[],isTop:false,createdAt:randomDate(threeDaysAgo,now),userId:null},
    {id:13,category:'car',brand:'Honda',model:'Accord',year:2019,price:22000,currency:'$',mileage:58000,engine:'2.4 л',transmission:'Вариатор',fuel:'Бензин',city:'Тирасполь',registration:'ПМР',description:'Японская надежность',photos:[],isTop:false,createdAt:randomDate(sevenDaysAgo,monthAgo),userId:null},
    {id:14,category:'car',brand:'Nissan',model:'Qashqai',year:2018,price:18500,currency:'€',mileage:72000,engine:'1.6 л',transmission:'Вариатор',fuel:'Бензин',city:'Григориополь',registration:'ПМР',description:'Семейный',photos:[],isTop:false,createdAt:randomDate(threeDaysAgo,now),userId:null},
    {id:15,category:'car',brand:'Ford',model:'Focus',year:2017,price:11000,currency:'$',mileage:95000,engine:'1.6 л',transmission:'Механика',fuel:'Бензин',city:'Дубоссары',registration:'ПМР',description:'В хорошем состоянии',photos:[],isTop:false,createdAt:randomDate(sevenDaysAgo,monthAgo),userId:null},
    {id:16,category:'car',brand:'Chevrolet',model:'Cruze',year:2016,price:9500,currency:'$',mileage:110000,engine:'1.8 л',transmission:'Автомат',fuel:'Бензин',city:'Каменка',registration:'ПМР',description:'Недорого',photos:[],isTop:false,createdAt:randomDate(sevenDaysAgo,monthAgo),userId:null},
    {id:17,category:'car',brand:'Skoda',model:'Rapid',year:2020,price:14500,currency:'€',mileage:38000,engine:'1.6 л',transmission:'Автомат',fuel:'Бензин',city:'Слободзея',registration:'ПМР',description:'Экономичный',photos:[],isTop:false,createdAt:randomDate(threeDaysAgo,now),userId:null},
    {id:18,category:'car',brand:'Renault',model:'Logan',year:2018,price:8500,currency:'$',mileage:88000,engine:'1.6 л',transmission:'Механика',fuel:'Бензин',city:'Бендеры',registration:'Молдова',description:'Простой и надежный',photos:[],isTop:false,createdAt:randomDate(sevenDaysAgo,monthAgo),userId:null},
    {id:19,category:'car',brand:'Lada',model:'Vesta',year:2021,price:9800,currency:'$',mileage:22000,engine:'1.6 л',transmission:'Механика',fuel:'Бензин',city:'Кагул',registration:'Молдова',description:'Новая Лада',photos:[],isTop:false,createdAt:randomDate(threeDaysAgo,now),userId:null},
    {id:20,category:'truck',brand:'MAN',model:'TGX',year:2019,price:68000,currency:'€',mileage:320000,engine:'12.4 л',transmission:'Автомат',fuel:'Дизель',city:'Тирасполь',registration:'ПМР',description:'Тягач',photos:[],isTop:true,createdAt:randomDate(sevenDaysAgo,monthAgo),userId:null},
    {id:21,category:'truck',brand:'Volvo',model:'FH16',year:2017,price:62000,currency:'€',mileage:450000,engine:'13.0 л',transmission:'Автомат',fuel:'Дизель',city:'Рыбница',registration:'ПМР',description:'Мощный тягач',photos:[],isTop:false,createdAt:randomDate(sevenDaysAgo,monthAgo),userId:null},
    {id:22,category:'truck',brand:'Scania',model:'R',year:2020,price:85000,currency:'€',mileage:220000,engine:'13.0 л',transmission:'Автомат',fuel:'Дизель',city:'Кишинёв',registration:'Молдова',description:'Отличное состояние',photos:[],isTop:false,createdAt:randomDate(threeDaysAgo,now),userId:null},
    {id:23,category:'truck',brand:'Kamaz',model:'6520',year:2018,price:35000,currency:'$',mileage:180000,engine:'11.8 л',transmission:'Механика',fuel:'Дизель',city:'Тирасполь',registration:'ПМР',description:'Самосвал',photos:[],isTop:false,createdAt:randomDate(sevenDaysAgo,monthAgo),userId:null},
    {id:24,category:'moto',brand:'Honda',model:'CBR600',year:2019,price:12000,currency:'$',mileage:12000,engine:'0.6 л',transmission:'Механика',fuel:'Бензин',city:'Кишинёв',registration:'Молдова',description:'Спортбайк',photos:[],isTop:false,createdAt:randomDate(threeDaysAgo,now),userId:null},
    {id:25,category:'moto',brand:'Yamaha',model:'R1',year:2020,price:18000,currency:'$',mileage:8500,engine:'1.0 л',transmission:'Механика',fuel:'Бензин',city:'Тирасполь',registration:'ПМР',description:'Супербайк',photos:[],isTop:false,createdAt:randomDate(sevenDaysAgo,monthAgo),userId:null},
    {id:26,category:'moto',brand:'Kawasaki',model:'Ninja 650',year:2018,price:11500,currency:'$',mileage:15000,engine:'0.65 л',transmission:'Механика',fuel:'Бензин',city:'Бельцы',registration:'Молдова',description:'Зеленый монстр',photos:[],isTop:false,createdAt:randomDate(threeDaysAgo,now),userId:null},
    {id:27,category:'moto',brand:'Suzuki',model:'GSX-R600',year:2017,price:9800,currency:'$',mileage:22000,engine:'0.6 л',transmission:'Механика',fuel:'Бензин',city:'Рыбница',registration:'ПМР',description:'Надежный',photos:[],isTop:false,createdAt:randomDate(sevenDaysAgo,monthAgo),userId:null},
    {id:28,category:'special',brand:'JCB',model:'3CX',year:2019,price:68000,currency:'$',mileage:3200,engine:'4.4 л',transmission:'Гидравлика',fuel:'Дизель',city:'Тирасполь',registration:'ПМР',description:'Экскаватор-погрузчик',photos:[],isTop:false,createdAt:randomDate(threeDaysAgo,now),userId:null},
    {id:29,category:'special',brand:'Komatsu',model:'PC200',year:2018,price:85000,currency:'€',mileage:4800,engine:'5.9 л',transmission:'Гидравлика',fuel:'Дизель',city:'Кишинёв',registration:'Молдова',description:'Гусеничный экскаватор',photos:[],isTop:false,createdAt:randomDate(sevenDaysAgo,monthAgo),userId:null},
    {id:30,category:'special',brand:'Hitachi',model:'ZX210',year:2020,price:92000,currency:'$',mileage:2100,engine:'6.0 л',transmission:'Гидравлика',fuel:'Дизель',city:'Рыбница',registration:'ПМР',description:'Новый',photos:[],isTop:true,createdAt:randomDate(threeDaysAgo,now),userId:null},
    {id:31,category:'water',brand:'BRP',model:'Sea-Doo GTX',year:2020,price:16000,currency:'$',mileage:80,engine:'1.6 л',transmission:'Авто',fuel:'Бензин',city:'Днестровск',registration:'ПМР',description:'Гидроцикл премиум',photos:[],isTop:false,createdAt:randomDate(threeDaysAgo,now),userId:null},
    {id:32,category:'water',brand:'Kawasaki',model:'Jet Ski Ultra',year:2019,price:14500,currency:'$',mileage:120,engine:'1.5 л',transmission:'Авто',fuel:'Бензин',city:'Тирасполь',registration:'ПМР',description:'Мощный гидроцикл',photos:[],isTop:false,createdAt:randomDate(sevenDaysAgo,monthAgo),userId:null},
    {id:33,category:'car',brand:'Lexus',model:'RX',year:2020,price:52000,currency:'$',mileage:38000,engine:'3.5 л',transmission:'Автомат',fuel:'Бензин',city:'Кишинёв',registration:'Молдова',description:'Премиум кроссовер',photos:[],isTop:true,createdAt:randomDate(sevenDaysAgo,monthAgo),userId:null},
    {id:34,category:'car',brand:'Infiniti',model:'QX60',year:2019,price:45000,currency:'$',mileage:52000,engine:'3.5 л',transmission:'Вариатор',fuel:'Бензин',city:'Тирасполь',registration:'ПМР',description:'7 мест',photos:[],isTop:false,createdAt:randomDate(threeDaysAgo,now),userId:null},
    {id:35,category:'car',brand:'Subaru',model:'Outback',year:2021,price:32000,currency:'$',mileage:28000,engine:'2.5 л',transmission:'Вариатор',fuel:'Бензин',city:'Бельцы',registration:'Молдова',description:'Полный привод',photos:[],isTop:false,createdAt:randomDate(threeDaysAgo,now),userId:null},
    {id:36,category:'car',brand:'Mitsubishi',model:'Outlander',year:2020,price:24000,currency:'$',mileage:45000,engine:'2.4 л',transmission:'Вариатор',fuel:'Бензин',city:'Рыбница',registration:'ПМР',description:'Надежный кроссовер',photos:[],isTop:false,createdAt:randomDate(sevenDaysAgo,monthAgo),userId:null},
    {id:37,category:'car',brand:'Jeep',model:'Grand Cherokee',year:2018,price:38000,currency:'$',mileage:68000,engine:'3.6 л',transmission:'Автомат',fuel:'Бензин',city:'Кишинёв',registration:'Молдова',description:'Американский внедорожник',photos:[],isTop:false,createdAt:randomDate(threeDaysAgo,now),userId:null},
    {id:38,category:'car',brand:'Land Rover',model:'Discovery',year:2019,price:48000,currency:'€',mileage:55000,engine:'3.0 л',transmission:'Автомат',fuel:'Дизель',city:'Тирасполь',registration:'ПМР',description:'Премиум внедорожник',photos:[],isTop:true,createdAt:randomDate(sevenDaysAgo,monthAgo),userId:null},
    {id:39,category:'car',brand:'Toyota',model:'RAV4',year:2021,price:33000,currency:'$',mileage:25000,engine:'2.5 л',transmission:'Автомат',fuel:'Бензин',city:'Кишинёв',registration:'Молдова',description:'Гибрид AWD',photos:[],isTop:false,createdAt:randomDate(threeDaysAgo,now),userId:null},
    {id:40,category:'car',brand:'BMW',model:'X3',year:2020,price:38000,currency:'€',mileage:42000,engine:'2.0 л',transmission:'Автомат',fuel:'Дизель',city:'Тирасполь',registration:'ПМР',description:'xDrive',photos:[],isTop:false,createdAt:randomDate(threeDaysAgo,now),userId:null},
    {id:41,category:'car',brand:'Mercedes',model:'GLE',year:2020,price:62000,currency:'€',mileage:38000,engine:'3.0 л',transmission:'Автомат',fuel:'Дизель',city:'Кишинёв',registration:'Молдова',description:'4Matic',photos:[],isTop:true,createdAt:randomDate(sevenDaysAgo,monthAgo),userId:null},
    {id:42,category:'car',brand:'Audi',model:'Q5',year:2019,price:42000,currency:'€',mileage:55000,engine:'2.0 л',transmission:'Автомат',fuel:'Бензин',city:'Бельцы',registration:'Молдова',description:'Quattro Premium',photos:[],isTop:false,createdAt:randomDate(threeDaysAgo,now),userId:null},
    {id:43,category:'car',brand:'Volkswagen',model:'Tiguan',year:2021,price:29000,currency:'$',mileage:32000,engine:'2.0 л',transmission:'Автомат',fuel:'Бензин',city:'Рыбница',registration:'ПМР',description:'4Motion R-Line',photos:[],isTop:false,createdAt:randomDate(threeDaysAgo,now),userId:null},
    {id:44,category:'car',brand:'Hyundai',model:'Tucson',year:2020,price:24000,currency:'$',mileage:38000,engine:'2.0 л',transmission:'Автомат',fuel:'Дизель',city:'Тирасполь',registration:'ПМР',description:'Полная комплектация',photos:[],isTop:false,createdAt:randomDate(sevenDaysAgo,monthAgo),userId:null},
    {id:45,category:'car',brand:'Kia',model:'Sorento',year:2019,price:28000,currency:'$',mileage:52000,engine:'2.2 л',transmission:'Автомат',fuel:'Дизель',city:'Кагул',registration:'Молдова',description:'7 мест 4WD',photos:[],isTop:false,createdAt:randomDate(threeDaysAgo,now),userId:null},
    {id:46,category:'car',brand:'Mazda',model:'6',year:2018,price:18000,currency:'$',mileage:68000,engine:'2.5 л',transmission:'Автомат',fuel:'Бензин',city:'Григориополь',registration:'ПМР',description:'Седан бизнес класса',photos:[],isTop:false,createdAt:randomDate(sevenDaysAgo,monthAgo),userId:null},
    {id:47,category:'car',brand:'Honda',model:'CR-V',year:2020,price:29000,currency:'$',mileage:42000,engine:'1.5 л',transmission:'Вариатор',fuel:'Бензин',city:'Днестровск',registration:'ПМР',description:'Турбо AWD',photos:[],isTop:false,createdAt:randomDate(threeDaysAgo,now),userId:null},
    {id:48,category:'car',brand:'Nissan',model:'X-Trail',year:2019,price:23000,currency:'$',mileage:58000,engine:'2.0 л',transmission:'Вариатор',fuel:'Бензин',city:'Слободзея',registration:'ПМР',description:'7 мест',photos:[],isTop:false,createdAt:randomDate(sevenDaysAgo,monthAgo),userId:null},
    {id:49,category:'car',brand:'Ford',model:'Kuga',year:2020,price:26000,currency:'$',mileage:45000,engine:'2.0 л',transmission:'Автомат',fuel:'Бензин',city:'Дубоссары',registration:'ПМР',description:'EcoBoost AWD',photos:[],isTop:false,createdAt:randomDate(threeDaysAgo,now),userId:null},
    {id:50,category:'car',brand:'Skoda',model:'Octavia',year:2021,price:22000,currency:'€',mileage:28000,engine:'1.5 л',transmission:'Робот',fuel:'Бензин',city:'Каменка',registration:'ПМР',description:'TSI DSG',photos:[],isTop:false,createdAt:randomDate(threeDaysAgo,now),userId:null},
    {id:51,category:'truck',brand:'DAF',model:'XF',year:2019,price:72000,currency:'€',mileage:380000,engine:'12.9 л',transmission:'Автомат',fuel:'Дизель',city:'Кишинёв',registration:'Молдова',description:'Тягач седельный',photos:[],isTop:false,createdAt:randomDate(sevenDaysAgo,monthAgo),userId:null},
    {id:52,category:'truck',brand:'Iveco',model:'Stralis',year:2018,price:58000,currency:'€',mileage:420000,engine:'11.0 л',transmission:'Автомат',fuel:'Дизель',city:'Тирасполь',registration:'ПМР',description:'Euro 6',photos:[],isTop:false,createdAt:randomDate(threeDaysAgo,now),userId:null},
    {id:53,category:'truck',brand:'Renault',model:'T',year:2020,price:68000,currency:'€',mileage:280000,engine:'11.0 л',transmission:'Автомат',fuel:'Дизель',city:'Рыбница',registration:'ПМР',description:'High Sleeper Cab',photos:[],isTop:false,createdAt:randomDate(threeDaysAgo,now),userId:null},
    {id:54,category:'truck',brand:'Mercedes',model:'Arocs',year:2019,price:78000,currency:'€',mileage:220000,engine:'10.7 л',transmission:'Автомат',fuel:'Дизель',city:'Бельцы',registration:'Молдова',description:'Самосвал 8x4',photos:[],isTop:false,createdAt:randomDate(sevenDaysAgo,monthAgo),userId:null},
    {id:55,category:'moto',brand:'Ducati',model:'Monster',year:2020,price:16000,currency:'€',mileage:8500,engine:'0.8 л',transmission:'Механика',fuel:'Бензин',city:'Кишинёв',registration:'Молдова',description:'Naked bike',photos:[],isTop:false,createdAt:randomDate(threeDaysAgo,now),userId:null},
    {id:56,category:'moto',brand:'BMW',model:'R 1250 GS',year:2021,price:22000,currency:'€',mileage:12000,engine:'1.25 л',transmission:'Механика',fuel:'Бензин',city:'Тирасполь',registration:'ПМР',description:'Adventure',photos:[],isTop:false,createdAt:randomDate(threeDaysAgo,now),userId:null},
    {id:57,category:'moto',brand:'Yamaha',model:'MT-09',year:2019,price:11000,currency:'$',mileage:18000,engine:'0.85 л',transmission:'Механика',fuel:'Бензин',city:'Рыбница',registration:'ПМР',description:'Street fighter',photos:[],isTop:false,createdAt:randomDate(sevenDaysAgo,monthAgo),userId:null},
    {id:58,category:'moto',brand:'Kawasaki',model:'Z900',year:2020,price:12500,currency:'$',mileage:14000,engine:'0.95 л',transmission:'Механика',fuel:'Бензин',city:'Бендеры',registration:'Молдова',description:'Naked',photos:[],isTop:false,createdAt:randomDate(threeDaysAgo,now),userId:null},
    {id:59,category:'special',brand:'Volvo',model:'EC210',year:2019,price:88000,currency:'€',mileage:3800,engine:'5.7 л',transmission:'Гидравлика',fuel:'Дизель',city:'Тирасполь',registration:'ПМР',description:'Гусеничный',photos:[],isTop:false,createdAt:randomDate(sevenDaysAgo,monthAgo),userId:null},
    {id:60,category:'special',brand:'Hyundai',model:'R210',year:2020,price:82000,currency:'$',mileage:2900,engine:'5.9 л',transmission:'Гидравлика',fuel:'Дизель',city:'Кишинёв',registration:'Молдова',description:'Экскаватор 21т',photos:[],isTop:false,createdAt:randomDate(threeDaysAgo,now),userId:null},
    {id:61,category:'special',brand:'Doosan',model:'DX225',year:2018,price:75000,currency:'$',mileage:4200,engine:'5.9 л',transmission:'Гидравлика',fuel:'Дизель',city:'Рыбница',registration:'ПМР',description:'22 тонны',photos:[],isTop:false,createdAt:randomDate(sevenDaysAgo,monthAgo),userId:null},
    {id:62,category:'special',brand:'JCB',model:'4CX',year:2020,price:72000,currency:'€',mileage:2800,engine:'4.8 л',transmission:'Гидравлика',fuel:'Дизель',city:'Бельцы',registration:'Молдова',description:'Погрузчик-экскаватор',photos:[],isTop:false,createdAt:randomDate(threeDaysAgo,now),userId:null},
    {id:63,category:'water',brand:'Yamaha',model:'FX',year:2021,price:17000,currency:'$',mileage:60,engine:'1.8 л',transmission:'Авто',fuel:'Бензин',city:'Днестровск',registration:'ПМР',description:'Cruiser HO',photos:[],isTop:false,createdAt:randomDate(threeDaysAgo,now),userId:null},
    {id:64,category:'water',brand:'BRP',model:'Sea-Doo RXT',year:2020,price:19000,currency:'$',mileage:85,engine:'1.6 л',transmission:'Авто',fuel:'Бензин',city:'Тирасполь',registration:'ПМР',description:'Performance',photos:[],isTop:false,createdAt:randomDate(sevenDaysAgo,monthAgo),userId:null},
    {id:65,category:'water',brand:'Kawasaki',model:'Jet Ski STX',year:2019,price:13500,currency:'$',mileage:140,engine:'1.5 л',transmission:'Авто',fuel:'Бензин',city:'Кишинёв',registration:'Молдова',description:'Rec',photos:[],isTop:false,createdAt:randomDate(threeDaysAgo,now),userId:null},
    {id:66,category:'water',brand:'Yamaha',model:'GP1800',year:2021,price:18500,currency:'$',mileage:45,engine:'1.8 л',transmission:'Авто',fuel:'Бензин',city:'Днестровск',registration:'ПМР',description:'SVHO',photos:[],isTop:false,createdAt:randomDate(threeDaysAgo,now),userId:null},
    {id:67,category:'car',brand:'Toyota',model:'Land Cruiser',year:2019,price:68000,currency:'$',mileage:82000,engine:'4.5 л',transmission:'Автомат',fuel:'Дизель',city:'Кишинёв',registration:'Молдова',description:'Prado 150',photos:[],isTop:true,createdAt:randomDate(sevenDaysAgo,monthAgo),userId:null},
    {id:68,category:'car',brand:'Lexus',model:'LX',year:2020,price:92000,currency:'$',mileage:48000,engine:'5.7 л',transmission:'Автомат',fuel:'Бензин',city:'Тирасполь',registration:'ПМР',description:'570 Full',photos:[],isTop:true,createdAt:randomDate(sevenDaysAgo,monthAgo),userId:null},
    
    // +30 НОВЫХ ОБЪЯВЛЕНИЙ
    {id:69,category:'car',brand:'Tesla',model:'Model 3',year:2022,price:45000,currency:'$',mileage:15000,engine:'Электро',transmission:'Автомат',fuel:'Электро',city:'Кишинёв',registration:'Молдова',description:'Автопилот, Long Range',photos:[],isTop:true,createdAt:randomDate(threeDaysAgo,now),userId:null},
    {id:70,category:'car',brand:'Porsche',model:'Cayenne',year:2020,price:85000,currency:'€',mileage:35000,engine:'3.0 л',transmission:'Автомат',fuel:'Бензин',city:'Тирасполь',registration:'ПМР',description:'Turbo, полная комплектация',photos:[],isTop:true,createdAt:randomDate(threeDaysAgo,now),userId:null},
    {id:71,category:'car',brand:'Volvo',model:'XC90',year:2021,price:65000,currency:'$',mileage:28000,engine:'2.0 л',transmission:'Автомат',fuel:'Бензин',city:'Бельцы',registration:'Молдова',description:'Hybrid, 7 мест',photos:[],isTop:false,createdAt:randomDate(sevenDaysAgo,monthAgo),userId:null},
    {id:72,category:'car',brand:'Genesis',model:'GV80',year:2022,price:58000,currency:'$',mileage:12000,engine:'3.5 л',transmission:'Автомат',fuel:'Бензин',city:'Кишинёв',registration:'Молдова',description:'Премиум класс',photos:[],isTop:false,createdAt:randomDate(threeDaysAgo,now),userId:null},
    {id:73,category:'car',brand:'Alfa Romeo',model:'Stelvio',year:2019,price:42000,currency:'€',mileage:45000,engine:'2.0 л',transmission:'Автомат',fuel:'Бензин',city:'Тирасполь',registration:'ПМР',description:'Quadrifoglio',photos:[],isTop:false,createdAt:randomDate(sevenDaysAgo,monthAgo),userId:null},
    {id:74,category:'car',brand:'Jaguar',model:'F-Pace',year:2020,price:48000,currency:'$',mileage:38000,engine:'2.0 л',transmission:'Автомат',fuel:'Дизель',city:'Рыбница',registration:'ПМР',description:'R-Sport',photos:[],isTop:false,createdAt:randomDate(threeDaysAgo,now),userId:null},
    {id:75,category:'car',brand:'Peugeot',model:'3008',year:2021,price:28000,currency:'€',mileage:25000,engine:'1.5 л',transmission:'Автомат',fuel:'Дизель',city:'Кишинёв',registration:'Молдова',description:'GT Line',photos:[],isTop:false,createdAt:randomDate(threeDaysAgo,now),userId:null},
    {id:76,category:'car',brand:'Citroen',model:'C5',year:2020,price:24000,currency:'$',mileage:32000,engine:'1.6 л',transmission:'Автомат',fuel:'Бензин',city:'Бельцы',registration:'Молдова',description:'Aircross',photos:[],isTop:false,createdAt:randomDate(sevenDaysAgo,monthAgo),userId:null},
    {id:77,category:'car',brand:'Seat',model:'Ateca',year:2019,price:22000,currency:'€',mileage:48000,engine:'1.5 л',transmission:'Робот',fuel:'Бензин',city:'Тирасполь',registration:'ПМР',description:'FR',photos:[],isTop:false,createdAt:randomDate(threeDaysAgo,now),userId:null},
    {id:78,category:'car',brand:'Haval',model:'Jolion',year:2022,price:25000,currency:'$',mileage:8000,engine:'1.5 л',transmission:'Робот',fuel:'Бензин',city:'Кишинёв',registration:'Молдова',description:'Новый, гарантия',photos:[],isTop:true,createdAt:randomDate(threeDaysAgo,now),userId:null},
    {id:79,category:'car',brand:'BYD',model:'Tang',year:2023,price:48000,currency:'$',mileage:5000,engine:'Hybrid',transmission:'Автомат',fuel:'Гибрид',city:'Тирасполь',registration:'ПМР',description:'Plug-in hybrid, 7 мест',photos:[],isTop:true,createdAt:randomDate(threeDaysAgo,now),userId:null},
    {id:80,category:'car',brand:'Geely',model:'Monjaro',year:2023,price:32000,currency:'$',mileage:3000,engine:'2.0 л',transmission:'Робот',fuel:'Бензин',city:'Бельцы',registration:'Молдова',description:'Flagship',photos:[],isTop:false,createdAt:randomDate(threeDaysAgo,now),userId:null},
    {id:81,category:'car',brand:'Chery',model:'Tiggo 8',year:2021,price:22000,currency:'$',mileage:35000,engine:'1.6 л',transmission:'Робот',fuel:'Бензин',city:'Рыбница',registration:'ПМР',description:'7 мест',photos:[],isTop:false,createdAt:randomDate(sevenDaysAgo,monthAgo),userId:null},
    {id:82,category:'car',brand:'Lincoln',model:'Navigator',year:2020,price:72000,currency:'$',mileage:42000,engine:'3.5 л',transmission:'Автомат',fuel:'Бензин',city:'Кишинёв',registration:'Молдова',description:'Black Label, люкс',photos:[],isTop:true,createdAt:randomDate(sevenDaysAgo,monthAgo),userId:null},
    {id:83,category:'car',brand:'Cadillac',model:'Escalade',year:2021,price:88000,currency:'$',mileage:28000,engine:'6.2 л',transmission:'Автомат',fuel:'Бензин',city:'Тирасполь',registration:'ПМР',description:'Premium Luxury',photos:[],isTop:true,createdAt:randomDate(threeDaysAgo,now),userId:null},
    {id:84,category:'car',brand:'Mini',model:'Cooper',year:2019,price:24000,currency:'€',mileage:38000,engine:'1.5 л',transmission:'Автомат',fuel:'Бензин',city:'Кишинёв',registration:'Молдова',description:'S Countryman',photos:[],isTop:false,createdAt:randomDate(sevenDaysAgo,monthAgo),userId:null},
    {id:85,category:'truck',brand:'Kenworth',model:'T680',year:2019,price:95000,currency:'$',mileage:450000,engine:'15.0 л',transmission:'Автомат',fuel:'Дизель',city:'Тирасполь',registration:'ПМР',description:'Американский тягач',photos:[],isTop:false,createdAt:randomDate(sevenDaysAgo,monthAgo),userId:null},
    {id:86,category:'truck',brand:'Freightliner',model:'Cascadia',year:2020,price:105000,currency:'$',mileage:380000,engine:'14.8 л',transmission:'Автомат',fuel:'Дизель',city:'Кишинёв',registration:'Молдова',description:'Sleeper cab',photos:[],isTop:false,createdAt:randomDate(threeDaysAgo,now),userId:null},
    {id:87,category:'truck',brand:'Hino',model:'500',year:2021,price:62000,currency:'$',mileage:120000,engine:'7.7 л',transmission:'Механика',fuel:'Дизель',city:'Рыбница',registration:'ПМР',description:'Японское качество',photos:[],isTop:false,createdAt:randomDate(threeDaysAgo,now),userId:null},
    {id:88,category:'special',brand:'Bobcat',model:'S205',year:2020,price:42000,currency:'$',mileage:1200,engine:'2.4 л',transmission:'Гидростатика',fuel:'Дизель',city:'Тирасполь',registration:'ПМР',description:'Минипогрузчик',photos:[],isTop:false,createdAt:randomDate(sevenDaysAgo,monthAgo),userId:null},
    {id:89,category:'special',brand:'Case',model:'CX210',year:2019,price:115000,currency:'€',mileage:2800,engine:'6.7 л',transmission:'Гидравлика',fuel:'Дизель',city:'Кишинёв',registration:'Молдова',description:'Экскаватор 21т',photos:[],isTop:false,createdAt:randomDate(threeDaysAgo,now),userId:null},
    {id:90,category:'special',brand:'John Deere',model:'310',year:2021,price:98000,currency:'$',mileage:1500,engine:'4.5 л',transmission:'Гидравлика',fuel:'Дизель',city:'Бельцы',registration:'Молдова',description:'Погрузчик-экскаватор',photos:[],isTop:false,createdAt:randomDate(threeDaysAgo,now),userId:null},
    {id:91,category:'moto',brand:'Triumph',model:'Street Triple',year:2021,price:14500,currency:'€',mileage:8500,engine:'0.76 л',transmission:'Механика',fuel:'Бензин',city:'Кишинёв',registration:'Молдова',description:'RS',photos:[],isTop:false,createdAt:randomDate(threeDaysAgo,now),userId:null},
    {id:92,category:'moto',brand:'KTM',model:'1290 Super Duke',year:2020,price:17000,currency:'€',mileage:12000,engine:'1.3 л',transmission:'Механика',fuel:'Бензин',city:'Тирасполь',registration:'ПМР',description:'R, beast mode',photos:[],isTop:false,createdAt:randomDate(sevenDaysAgo,monthAgo),userId:null},
    {id:93,category:'moto',brand:'Aprilia',model:'RSV4',year:2021,price:18500,currency:'€',mileage:6500,engine:'1.1 л',transmission:'Механика',fuel:'Бензин',city:'Бельцы',registration:'Молдова',description:'Factory',photos:[],isTop:false,createdAt:randomDate(threeDaysAgo,now),userId:null},
    {id:94,category:'moto',brand:'Indian',model:'Scout',year:2020,price:15500,currency:'$',mileage:9500,engine:'1.1 л',transmission:'Механика',fuel:'Бензин',city:'Кишинёв',registration:'Молдова',description:'Bobber',photos:[],isTop:false,createdAt:randomDate(sevenDaysAgo,monthAgo),userId:null},
    {id:95,category:'water',brand:'Yamaha',model:'SuperJet',year:2022,price:11000,currency:'$',mileage:25,engine:'1.0 л',transmission:'Jet',fuel:'Бензин',city:'Днестровск',registration:'ПМР',description:'Stand-up',photos:[],isTop:false,createdAt:randomDate(threeDaysAgo,now),userId:null},
    {id:96,category:'water',brand:'BRP',model:'Sea-Doo Spark',year:2021,price:8500,currency:'$',mileage:45,engine:'0.9 л',transmission:'Авто',fuel:'Бензин',city:'Тирасполь',registration:'ПМР',description:'Trixx',photos:[],isTop:false,createdAt:randomDate(threeDaysAgo,now),userId:null},
    {id:97,category:'water',brand:'Kawasaki',model:'Jet Ski SX-R',year:2020,price:12500,currency:'$',mileage:35,engine:'1.5 л',transmission:'Jet',fuel:'Бензин',city:'Днестровск',registration:'ПМР',description:'Stand-up',photos:[],isTop:false,createdAt:randomDate(sevenDaysAgo,monthAgo),userId:null},
    {id:98,category:'water',brand:'Yamaha',model:'VX Cruiser',year:2023,price:16500,currency:'$',mileage:10,engine:'1.8 л',transmission:'Авто',fuel:'Бензин',city:'Кишинёв',registration:'Молдова',description:'HO, новый',photos:[],isTop:true,createdAt:randomDate(threeDaysAgo,now),userId:null}
  ];
}
